---
driver_plugin: vagrant
platforms:
- name: centos-6.5
- name: centos-6.6
- name: ubuntu-12.04
- name: ubuntu-14.10
#  driver_config:
#    box: precise-64-lxc-preseed
#    box_url: http://vagrant.hw-ops.com/precise-64-lxc-preseed.box
#    box: precise-64
#    box_url: https://github.com/downloads/chrisroberts/vagrant-boxes/precise-64.box
#    box: opscode-ubuntu-12.04
#    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/boxes/opscode-ubuntu-12.04.box
suites:
- name: default
  run_list:
  - recipe[lxc-test]
