---
driver:
  name: vagrant
  require_chef_omnibus: '11.18.6'

platforms:
- name: ubuntu-12.04
- name: ubuntu-14.04

suites:
- name: default
  provisioner:
    name: chef_solo
  run_list:
    - 'recipe[vagabond]'
  attributes:
    lxc:
      enable_daily_ppa: true
    vagabond:
      bases:
        centos_5:
          enabled: false
        centos_6:
          enabled: true
        centos_7:
          enabled: true
        ubuntu_1204:
          enabled: true
        ubuntu_1404:
          enabled: true
        debian_6:
          enabled: true
        debian_7:
          enabled: true
        debian_8:
          enabled: true
- name: test-container
  provisioner:
    name: chef_zero
  run_list:
    - 'recipe[lxc-test::container]'
  attributes:
    chef_client:
      config:
        chef_server_url: 'http://10.0.3.1:8889'
