---
driver:
  name: vagrant
  require_chef_omnibus: '11.18.6'

platforms:
- name: ubuntu-12.04
- name: ubuntu-14.04

suites:
- name: default
  provisioner:
    name: chef_solo
  run_list:
    - 'recipe[lxc-test::default]'
  attributes:
- name: test-container
  provisioner:
    name: chef_zero
  run_list:
    - 'recipe[lxc-test::container]'
  attributes:
    chef_client:
      config:
        chef_server_url: 'http://10.0.3.1:8889'
