name             'lxc'
maintainer       'Chris Roberts'
maintainer_email 'chris@hw-ops.com'
license          'Apache-2.0'
description      'Chef driven Linux Containers'
version          '2.0.0'

depends 'dpkg_autostart', '>= 0.1.10'
depends 'polipo'
depends 'iptables-ng'
